config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'chatroom#index'
  get '/users', to: 'chatroom#index'

  post '/message', to: 'messages#create'
  get '/messages_with_button', to: 'chatroom#index_with_button', as: 'messages_with_button'
  delete '/likes', to: 'likes#destroy'

  resources :likes, only: %i[create]

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/like.rb
# frozen_string_literal: true

class Like < ApplicationRecord
  belongs_to :user
  belongs_to :message
end

app/models/message.rb
# frozen_string_literal: true

class Message < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy

  validates :body, length: { minimum: 1, maximum: 240 }

  def likes_count
    likes.where(message_id: id).count
  end

  def liked?(user)
    return false unless user

    likes.exists?(message_id: id, user_id: user.id)
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :messages, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_one_attached :avatar

  validates :username, presence: true, length: { minimum: 3, maximum: 15 },
                       uniqueness: { case_sensitive: false }

  validate :avatar_file_type

  private

  def avatar_file_type
    return if avatar.blob.nil? || avatar.blob.content_type.include?('image')

    errors.add(:avatar, 'must be an image')
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include UserStatus

  before_action :configure_permitted_parameters, if: :devise_controller?

  def current_app_user
    @current_app_user ||= current_user
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update, keys: %i[username avatar])
  end
end

app/controllers/chatroom_controller.rb
# frozen_string_literal: true

class ChatroomController < ApplicationController
  def index
    @message = Message.new
    messages_load(1)
  end

  def index_with_button
    messages_load(params[:page])
  end

  private

  def messages_load(page)
    @messages = Message
                .includes(:likes, user: :avatar_blob)
                .order('created_at DESC')
                .paginate(page:, per_page: 10)

    respond_to do |format|
      format.html
      format.js
    end
  end
end

app/controllers/concerns/user_status.rb
# frozen_string_literal: true

module UserStatus
  extend ActiveSupport::Concern

  def require_user
    return if current_app_user

    flash[:alert] = 'You must log in to do this action'
    redirect_to new_user_session_path
  end

  def logged_in_redirect
    return unless current_app_user

    flash[:alert] = 'You are already logged in'
    redirect_to root_path
  end
end

app/controllers/likes_controller.rb
# frozen_string_literal: true

class LikesController < ApplicationController
  before_action :require_user
  def create
    Like.find_or_create_by!(user_id: current_app_user.id, message_id: message_param_id)

    broadcast_like_counter
  end

  def destroy
    Like.destroy_by(user_id: current_app_user.id, message_id: message_param_id)

    broadcast_like_counter
  end

  private

  def like_params
    params.require(:like).permit(:message_id)
  end

  def message_param_id
    like_params[:message_id]
  end

  def broadcast_like_counter
    @message ||= Message.includes(:likes).find(message_param_id)
    ActionCable.server.broadcast('chatroom_channel',
                                 { message_id: message_param_id, like_count: @message.likes_count })
  end
end

app/controllers/messages_controller.rb
# frozen_string_literal: true

class MessagesController < ApplicationController
  before_action :require_user
  def create
    message = current_app_user.messages.build(message_params)
    return unless message.save

    ActionCable.server.broadcast('chatroom_channel', { message: message_render(message) })
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: { message: })
  end
end

app/controllers/turbo_devise_controller.rb
# frozen_string_literal: true

class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      if get?
        raise e
      elsif has_errors? && default_action
        render rendering_options.merge(formats: :html, status: :unprocessable_entity)
      else
        redirect_to navigation_location
      end
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

module Users
  class RegistrationsController < Devise::RegistrationsController
    include UserStatus

    before_action :logged_in_redirect, only: :create
    def create
      super
      flash[:alert] = resource.errors.full_messages
    end
    
    private

    def user_params
      params.require(:user).permit(:username, :email, :password,
                                   :password_confirmation, :current_password, :avatar)
    end
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

module Users
  class SessionsController < Devise::SessionsController
    include UserStatus

    before_action :logged_in_redirect, only: %i[new create]
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
  def user_avatar(user)
    if user.avatar.attached? && user.valid?
      user.avatar
    else
      "https://secure.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}.png?d=mp"
    end
  end
end

app/views/chatroom/index.html.erb
<h2 class="ui center aligned icon header">
  <i class="circular inverted blue comment icon icon"></i>
  Say something to everyone!
</h2>
<div class="ui two column grid">
  <div class="twelve wide column">
    <div class="ui bottom-started fluid raised card chatbox">
      <div class="scrollable content">
        <div class="ui small feed" id="messagesContainer">
          <div id="withButton">
            <%= will_paginate @messages %>
          </div>

          <% if @messages.next_page %>
            <div id="loadMoreMessages" class="center aligned">
              <button class="ui primary small basic button">More messages</button>
            </div>
          <% end %>
          <%= render @messages.reverse %>
        </div>
      </div>
      <div class="extra content">
        <%= form_for(@message, html: { class: 'ui reply form', role: 'form' }, url: message_path, remote: true) do |f| %>
          <div class="field">
            <div class="ui fluid icon input <%= 'disabled' unless current_user %>">
              <%= f.text_field :body, placeholder: 'Write a message...' %>
              <%= f.button '<i class="chevron circle right icon"></i>'.html_safe, class: "ui blue inverted icon button", id: 'submit_message' %>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>

  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
      <div class="content">
        <div class="ui inverted vertical menu">
          <a class="active item">
            Home
          </a>
          <a class="item">
            Messages
          </a>
          <a class="item">
            Friends
          </a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/chatroom/index_with_button.js.erb
$('#messagesContainer').prepend('<%= j render @messages.reverse %>');
<% if @messages.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @messages %>');
  $('.pagination').hide();
  $('.pagination, #loadMoreMessages').prependTo('#messagesContainer');
<% else %>
  $('.pagination, #loadMoreMessages').remove();
<% end %>

app/views/layouts/_confirmation_modal.html.erb
<div class="ui basic modal" id="<%= modal_id %>">
  <div class="ui icon header">
    <i class="archive icon"></i>
    <%= header.html_safe %>
  </div>
  <div class="content">
    <%= content.html_safe %>
  </div>
  <div class="actions">
    <%= button.html_safe %>
  </div>
</div>

app/views/layouts/_likes.html.erb
<%= link_to '<i class="like icon"></i> 11 Likes'.html_safe, likes_path(user_id: message.user.id, message_id: message.id), class: 'like' %>

app/views/layouts/_messages.html.erb
<% flash.each do |message_type, message_content| %>
  <% next if message_content.blank? %>
  <div class="ui <%= message_type == 'notice' ? 'success' : 'error' %> message transition">
    <i class="close icon"></i>
      <ul class="list">
        <% Array(message_content).each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<a class="item" href="/">
  Chatroom
</a>
<a class="item">
  Messages
</a>
<div class="right menu">
  <div class="ui dropdown item">
    Account <i class="dropdown icon"></i>
    <div class="menu">
      <% if current_user %>
        <%= link_to 'Edit', edit_user_registration_path, class: 'item' %>
        <%= link_to 'Log out', destroy_user_session_path, class: 'item',
            data: {turbo_method: :delete, turbo_confirm: 'Are you sure you want to log out?'}%>
      <% else %>
        <%= link_to 'Login', new_user_session_path, class: 'item' %>
        <%= link_to 'Sign up', new_user_registration_path, class: 'item' %>
      <% end %>
    </div>
  </div>
  <div class="item">
    <% if current_user %>
      <%= button_to 'Log out', destroy_user_session_path, method: :delete, class: 'ui primary button' %>
    <% else %>
        <%= button_to 'Login', new_user_session_path, method: :get, class: 'ui primary button' %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ChatPat</title>
  <%= favicon_link_tag %>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <link
    rel="stylesheet"
    href="https://cdn.jsdelivr.net/npm/semantic-ui@2.5.0/dist/semantic.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.1/jquery.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.5.0/dist/semantic.min.js"></script>
</head>

<body>
<div class="ui inverted large menu">
  <div class="ui container">
    <%= render 'layouts/navigation' %>
  </div>
</div>
<div class="ui container">
  <%= render 'layouts/messages' %>
  <%= yield %>
</div>
</body>
</html>

app/views/messages/_message.html.erb
<div class="event" id="message<%= message.id %>">
  <div class="label">
    <%= image_tag user_avatar(message.user) %>
  </div>
  <div class="content">
    <div class="summary">
      <a class="user">
        <%= message.user.username %>
      </a>
      <div class="date">
        <%= time_ago_in_words(message.created_at) %> ago
      </div>
    </div>
    <div class="extra text">
      <%= message.body %>
    </div>
    <div class="meta">
      <%= link_to "<i class=\"like icon\"></i> <span id=\"likeCount\">#{message.likes_count}</span> Likes".html_safe,
                  likes_path(like: { message_id: message.id }),
                  class: "like likeButton #{ 'liked' if message.liked?(current_user) }",
                  data: {turbo_method: message.liked?(current_user) ? :delete : :post}
      %>
    </div>
  </div>
</div>